/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Color;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author alumno
 */
public class VentanaGestor extends JFrame {

    private VentanaIndex e;
    private Usuario u;

    public VentanaGestor(VentanaIndex e, Usuario u) {
        initComponents();
        getContentPane().setBackground(new Color(90, 37, 193));
        setLocationRelativeTo(null);
        setVisible(true);
        this.e = e;
        this.u = u;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContent = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelCuentaBanco = new javax.swing.JPanel();
        retiraSaldoButton = new javax.swing.JButton();
        ingresaSaldoButton = new javax.swing.JButton();
        addCuentaBancoButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelTrabajo = new javax.swing.JPanel();
        addAntiguedadButton = new javax.swing.JButton();
        trabajarButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        panelUsuario = new javax.swing.JPanel();
        CambiaTrabajoButton = new javax.swing.JButton();
        cambiaNombreButton = new javax.swing.JButton();
        infoBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelCuentaNetflix = new javax.swing.JPanel();
        cobrarButton = new javax.swing.JButton();
        addPerfilButton = new javax.swing.JButton();
        addCuentaNetflixButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        closeLbl = new javax.swing.JLabel();
        minLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContent.setBackground(new java.awt.Color(90, 37, 153));
        panelContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(153, 0, 102));
        labelTitulo.setText("GESTOR USUARIO");
        panelContent.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        panelCuentaBanco.setBackground(new java.awt.Color(73, 21, 91));
        panelCuentaBanco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        retiraSaldoButton.setBackground(new java.awt.Color(90, 37, 153));
        retiraSaldoButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        retiraSaldoButton.setForeground(new java.awt.Color(255, 255, 255));
        retiraSaldoButton.setText("Retirar Saldo");

        ingresaSaldoButton.setBackground(new java.awt.Color(90, 37, 153));
        ingresaSaldoButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        ingresaSaldoButton.setForeground(new java.awt.Color(255, 255, 255));
        ingresaSaldoButton.setText("Ingresar Saldo");

        addCuentaBancoButton.setBackground(new java.awt.Color(90, 37, 153));
        addCuentaBancoButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        addCuentaBancoButton.setForeground(new java.awt.Color(255, 255, 255));
        addCuentaBancoButton.setText("Añadir Cuenta Banco");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CUENTA BANCO");

        javax.swing.GroupLayout panelCuentaBancoLayout = new javax.swing.GroupLayout(panelCuentaBanco);
        panelCuentaBanco.setLayout(panelCuentaBancoLayout);
        panelCuentaBancoLayout.setHorizontalGroup(
            panelCuentaBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuentaBancoLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panelCuentaBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuentaBancoLayout.createSequentialGroup()
                        .addGroup(panelCuentaBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ingresaSaldoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addCuentaBancoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(retiraSaldoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuentaBancoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(53, 53, 53))))
        );
        panelCuentaBancoLayout.setVerticalGroup(
            panelCuentaBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuentaBancoLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addComponent(addCuentaBancoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingresaSaldoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retiraSaldoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        panelContent.add(panelCuentaBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 190, 180));

        panelTrabajo.setBackground(new java.awt.Color(73, 21, 91));
        panelTrabajo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        addAntiguedadButton.setBackground(new java.awt.Color(90, 37, 153));
        addAntiguedadButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        addAntiguedadButton.setForeground(new java.awt.Color(255, 255, 255));
        addAntiguedadButton.setText("Añadir Antiguedad");

        trabajarButton.setBackground(new java.awt.Color(90, 37, 153));
        trabajarButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        trabajarButton.setForeground(new java.awt.Color(255, 255, 255));
        trabajarButton.setText("Trabajar");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TRABAJO");

        javax.swing.GroupLayout panelTrabajoLayout = new javax.swing.GroupLayout(panelTrabajo);
        panelTrabajo.setLayout(panelTrabajoLayout);
        panelTrabajoLayout.setHorizontalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trabajarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addAntiguedadButton, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrabajoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(59, 59, 59))
        );
        panelTrabajoLayout.setVerticalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrabajoLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(trabajarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addAntiguedadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        panelContent.add(panelTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 170, 180));

        panelUsuario.setBackground(new java.awt.Color(73, 21, 91));
        panelUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        CambiaTrabajoButton.setBackground(new java.awt.Color(90, 37, 153));
        CambiaTrabajoButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        CambiaTrabajoButton.setForeground(new java.awt.Color(255, 255, 255));
        CambiaTrabajoButton.setText("Cambiar Trabajo");
        CambiaTrabajoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiaTrabajoButtonActionPerformed(evt);
            }
        });

        cambiaNombreButton.setBackground(new java.awt.Color(90, 37, 153));
        cambiaNombreButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        cambiaNombreButton.setForeground(new java.awt.Color(255, 255, 255));
        cambiaNombreButton.setText("Cambiar Nombre");
        cambiaNombreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiaNombreButtonActionPerformed(evt);
            }
        });

        infoBtn.setBackground(new java.awt.Color(90, 37, 153));
        infoBtn.setForeground(new java.awt.Color(255, 255, 255));
        infoBtn.setText("Informacion Usuario");
        infoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBtnActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIO");

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(infoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cambiaNombreButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(CambiaTrabajoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(60, 60, 60))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(cambiaNombreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CambiaTrabajoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelContent.add(panelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 170, 180));

        panelCuentaNetflix.setBackground(new java.awt.Color(73, 21, 91));
        panelCuentaNetflix.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        cobrarButton.setBackground(new java.awt.Color(90, 37, 153));
        cobrarButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        cobrarButton.setForeground(new java.awt.Color(255, 255, 255));
        cobrarButton.setText("Cobrar");

        addPerfilButton.setBackground(new java.awt.Color(90, 37, 153));
        addPerfilButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        addPerfilButton.setForeground(new java.awt.Color(255, 255, 255));
        addPerfilButton.setText("Añadir Perfil");

        addCuentaNetflixButton.setBackground(new java.awt.Color(90, 37, 153));
        addCuentaNetflixButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        addCuentaNetflixButton.setForeground(new java.awt.Color(255, 255, 255));
        addCuentaNetflixButton.setText("Añadir Cuenta Netflix");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CUENTA NETFLIX");

        javax.swing.GroupLayout panelCuentaNetflixLayout = new javax.swing.GroupLayout(panelCuentaNetflix);
        panelCuentaNetflix.setLayout(panelCuentaNetflixLayout);
        panelCuentaNetflixLayout.setHorizontalGroup(
            panelCuentaNetflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuentaNetflixLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCuentaNetflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addPerfilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addCuentaNetflixButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cobrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelCuentaNetflixLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCuentaNetflixLayout.setVerticalGroup(
            panelCuentaNetflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuentaNetflixLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(addCuentaNetflixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addPerfilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cobrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelContent.add(panelCuentaNetflix, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, 180));

        getContentPane().add(panelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 600, 550));

        header.setBackground(new java.awt.Color(153, 0, 255));
        header.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        closeLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        closeLbl.setText(" x ");
        closeLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLblMouseClicked(evt);
            }
        });

        minLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        minLbl.setText(" -");
        minLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 556, Short.MAX_VALUE)
                .addComponent(minLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeLbl))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(closeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(minLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CambiaTrabajoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiaTrabajoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CambiaTrabajoButtonActionPerformed

    private void cambiaNombreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiaNombreButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambiaNombreButtonActionPerformed

    private void closeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLblMouseClicked
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeLblMouseClicked

    private void minLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minLblMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minLblMouseClicked

    private int yMouse, xMouse;
    
    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void infoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBtnActionPerformed
        JOptionPane.showMessageDialog(this, u.toString());
    }//GEN-LAST:event_infoBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CambiaTrabajoButton;
    private javax.swing.JButton addAntiguedadButton;
    private javax.swing.JButton addCuentaBancoButton;
    private javax.swing.JButton addCuentaNetflixButton;
    private javax.swing.JButton addPerfilButton;
    private javax.swing.JButton cambiaNombreButton;
    private javax.swing.JLabel closeLbl;
    private javax.swing.JButton cobrarButton;
    private javax.swing.JPanel header;
    private javax.swing.JButton infoBtn;
    private javax.swing.JButton ingresaSaldoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel minLbl;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelCuentaBanco;
    private javax.swing.JPanel panelCuentaNetflix;
    private javax.swing.JPanel panelTrabajo;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JButton retiraSaldoButton;
    private javax.swing.JButton trabajarButton;
    // End of variables declaration//GEN-END:variables
}
