/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Color;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author alumno
 */
public class VentanaGestor extends javax.swing.JDialog {

    /**
     * Creates new form VentanaGestor
     */
    public VentanaGestor() {
        super();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        getContentPane().setBackground(new Color(90,37,193));
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContent = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelCuentaBanco = new javax.swing.JPanel();
        retiraSaldoButton = new javax.swing.JButton();
        ingresaSaldoButton = new javax.swing.JButton();
        addCuentaBancoButton = new javax.swing.JButton();
        panelTrabajo = new javax.swing.JPanel();
        addAntiguedadButton = new javax.swing.JButton();
        trabajarButton = new javax.swing.JButton();
        panelUsuario = new javax.swing.JPanel();
        CambiaTrabajoButton = new javax.swing.JButton();
        cambiaNombreButton = new javax.swing.JButton();
        panelCuentaNetflix = new javax.swing.JPanel();
        cobrarButton = new javax.swing.JButton();
        addPerfilButton = new javax.swing.JButton();
        addCuentaNetflixButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        panelContent.setBackground(new java.awt.Color(90, 37, 153));
        panelContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(153, 0, 102));
        labelTitulo.setText("GESTOR USUARIO");
        panelContent.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        panelCuentaBanco.setBackground(new java.awt.Color(73, 21, 91));
        panelCuentaBanco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        retiraSaldoButton.setBackground(new java.awt.Color(90, 37, 153));
        retiraSaldoButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        retiraSaldoButton.setForeground(new java.awt.Color(255, 255, 255));
        retiraSaldoButton.setText("Retirar Saldo");

        ingresaSaldoButton.setBackground(new java.awt.Color(90, 37, 153));
        ingresaSaldoButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        ingresaSaldoButton.setForeground(new java.awt.Color(255, 255, 255));
        ingresaSaldoButton.setText("Ingresar Saldo");

        addCuentaBancoButton.setBackground(new java.awt.Color(90, 37, 153));
        addCuentaBancoButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        addCuentaBancoButton.setForeground(new java.awt.Color(255, 255, 255));
        addCuentaBancoButton.setText("Añadir Cuenta Banco");

        javax.swing.GroupLayout panelCuentaBancoLayout = new javax.swing.GroupLayout(panelCuentaBanco);
        panelCuentaBanco.setLayout(panelCuentaBancoLayout);
        panelCuentaBancoLayout.setHorizontalGroup(
            panelCuentaBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuentaBancoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCuentaBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addCuentaBancoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ingresaSaldoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(retiraSaldoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelCuentaBancoLayout.setVerticalGroup(
            panelCuentaBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuentaBancoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(addCuentaBancoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingresaSaldoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retiraSaldoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        panelContent.add(panelCuentaBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 190, 180));

        panelTrabajo.setBackground(new java.awt.Color(73, 21, 91));
        panelTrabajo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        addAntiguedadButton.setBackground(new java.awt.Color(90, 37, 153));
        addAntiguedadButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        addAntiguedadButton.setForeground(new java.awt.Color(255, 255, 255));
        addAntiguedadButton.setText("Añadir Antiguedad");

        trabajarButton.setBackground(new java.awt.Color(90, 37, 153));
        trabajarButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        trabajarButton.setForeground(new java.awt.Color(255, 255, 255));
        trabajarButton.setText("Trabajar");

        javax.swing.GroupLayout panelTrabajoLayout = new javax.swing.GroupLayout(panelTrabajo);
        panelTrabajo.setLayout(panelTrabajoLayout);
        panelTrabajoLayout.setHorizontalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trabajarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addAntiguedadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTrabajoLayout.setVerticalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrabajoLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(trabajarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addAntiguedadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        panelContent.add(panelTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 170, 180));

        panelUsuario.setBackground(new java.awt.Color(73, 21, 91));
        panelUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        CambiaTrabajoButton.setBackground(new java.awt.Color(90, 37, 153));
        CambiaTrabajoButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        CambiaTrabajoButton.setForeground(new java.awt.Color(255, 255, 255));
        CambiaTrabajoButton.setText("Cambiar Trabajo");
        CambiaTrabajoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiaTrabajoButtonActionPerformed(evt);
            }
        });

        cambiaNombreButton.setBackground(new java.awt.Color(90, 37, 153));
        cambiaNombreButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        cambiaNombreButton.setForeground(new java.awt.Color(255, 255, 255));
        cambiaNombreButton.setText("Cambiar Nombre");
        cambiaNombreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiaNombreButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CambiaTrabajoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelUsuarioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cambiaNombreButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(CambiaTrabajoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelUsuarioLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(cambiaNombreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(87, Short.MAX_VALUE)))
        );

        panelContent.add(panelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 170, 180));

        panelCuentaNetflix.setBackground(new java.awt.Color(73, 21, 91));
        panelCuentaNetflix.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        cobrarButton.setBackground(new java.awt.Color(90, 37, 153));
        cobrarButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        cobrarButton.setForeground(new java.awt.Color(255, 255, 255));
        cobrarButton.setText("Cobrar");

        addPerfilButton.setBackground(new java.awt.Color(90, 37, 153));
        addPerfilButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        addPerfilButton.setForeground(new java.awt.Color(255, 255, 255));
        addPerfilButton.setText("Añadir Perfil");

        addCuentaNetflixButton.setBackground(new java.awt.Color(90, 37, 153));
        addCuentaNetflixButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        addCuentaNetflixButton.setForeground(new java.awt.Color(255, 255, 255));
        addCuentaNetflixButton.setText("Añadir Cuenta Netflix");

        javax.swing.GroupLayout panelCuentaNetflixLayout = new javax.swing.GroupLayout(panelCuentaNetflix);
        panelCuentaNetflix.setLayout(panelCuentaNetflixLayout);
        panelCuentaNetflixLayout.setHorizontalGroup(
            panelCuentaNetflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuentaNetflixLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCuentaNetflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addPerfilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addCuentaNetflixButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cobrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCuentaNetflixLayout.setVerticalGroup(
            panelCuentaNetflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuentaNetflixLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addCuentaNetflixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addPerfilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cobrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        panelContent.add(panelCuentaNetflix, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, 180));

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CambiaTrabajoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiaTrabajoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CambiaTrabajoButtonActionPerformed

    private void cambiaNombreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiaNombreButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambiaNombreButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CambiaTrabajoButton;
    private javax.swing.JButton addAntiguedadButton;
    private javax.swing.JButton addCuentaBancoButton;
    private javax.swing.JButton addCuentaNetflixButton;
    private javax.swing.JButton addPerfilButton;
    private javax.swing.JButton cambiaNombreButton;
    private javax.swing.JButton cobrarButton;
    private javax.swing.JButton ingresaSaldoButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelCuentaBanco;
    private javax.swing.JPanel panelCuentaNetflix;
    private javax.swing.JPanel panelTrabajo;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JButton retiraSaldoButton;
    private javax.swing.JButton trabajarButton;
    // End of variables declaration//GEN-END:variables
}
